import { TransactionType, TransactionStatus, type Transaction } from "@/types/transaction";

export const mockTransactions: Transaction[] = [
  {
    transaction_id: "txn_a1b2c3d4",
    type: TransactionType.CREDIT_CARD,
    amount: 2499.99,
    currency: "USD",
    timestamp: "2026-07-23T14:23:11Z",
    sender_id: "usr_8d2f1",
    receiver_id: "mrc_electronics",
    merchant_id: "mrc_electronics",
    channel: "online",
    ip_address: "185.234.12.44",
    device_id: "dev_iphone15_x1",
    country_code: "RO",
    description: "Electronics purchase - suspicious velocity",
    status: TransactionStatus.FLAGGED,
    risk_score: 0.92,
    risk_level: "CRITICAL",
    risk_verdict: "BLOCK",
    processing_time_ms: 14,
  },
  {
    transaction_id: "txn_e5f6g7h8",
    type: TransactionType.WIRE_TRANSFER,
    amount: 49800.0,
    currency: "USD",
    timestamp: "2026-07-23T14:21:45Z",
    sender_id: "usr_3a9c2",
    receiver_id: "usr_offshore_1",
    channel: "mobile_banking",
    ip_address: "103.41.22.8",
    device_id: "dev_pixel8_new",
    country_code: "SG",
    description: "High-value wire to new beneficiary",
    status: TransactionStatus.UNDER_REVIEW,
    risk_score: 0.87,
    risk_level: "VERY_HIGH",
    risk_verdict: "DECLINE",
    processing_time_ms: 22,
  },
  {
    transaction_id: "txn_i9j0k1l2",
    type: TransactionType.UPI,
    amount: 15000.0,
    currency: "INR",
    timestamp: "2026-07-23T14:19:33Z",
    sender_id: "usr_7b4e3",
    receiver_id: "usr_mule_suspect",
    channel: "mobile",
    ip_address: "49.36.128.55",
    device_id: "dev_samsung_a14",
    country_code: "IN",
    description: "UPI transfer to suspected mule account",
    status: TransactionStatus.BLOCKED,
    risk_score: 0.79,
    risk_level: "HIGH",
    risk_verdict: "BLOCK",
    processing_time_ms: 11,
  },
  {
    transaction_id: "txn_m3n4o5p6",
    type: TransactionType.CREDIT_CARD,
    amount: 89.99,
    currency: "USD",
    timestamp: "2026-07-23T14:18:22Z",
    sender_id: "usr_regular_1",
    receiver_id: "mrc_grocery",
    merchant_id: "mrc_grocery",
    channel: "pos",
    device_id: "dev_pos_terminal_42",
    country_code: "US",
    description: "Regular grocery purchase",
    status: TransactionStatus.APPROVED,
    risk_score: 0.02,
    risk_level: "VERY_LOW",
    risk_verdict: "APPROVE",
    processing_time_ms: 6,
  },
  {
    transaction_id: "txn_q7r8s9t0",
    type: TransactionType.CRYPTO,
    amount: 3.45,
    currency: "ETH",
    timestamp: "2026-07-23T14:15:08Z",
    sender_id: "usr_1e5d4",
    receiver_id: "wallet_mixer_sus",
    channel: "defi",
    ip_address: "45.33.32.156",
    country_code: "VN",
    description: "Transfer to known mixer address",
    status: TransactionStatus.FLAGGED,
    risk_score: 0.84,
    risk_level: "VERY_HIGH",
    risk_verdict: "DECLINE",
    processing_time_ms: 18,
  },
  {
    transaction_id: "txn_u1v2w3x4",
    type: TransactionType.P2P,
    amount: 500.0,
    currency: "USD",
    timestamp: "2026-07-23T14:12:55Z",
    sender_id: "usr_safe_2",
    receiver_id: "usr_friend_1",
    channel: "mobile",
    device_id: "dev_iphone14_y2",
    country_code: "US",
    description: "P2P payment to known contact",
    status: TransactionStatus.APPROVED,
    risk_score: 0.08,
    risk_level: "VERY_LOW",
    risk_verdict: "APPROVE",
    processing_time_ms: 5,
  },
  {
    transaction_id: "txn_y5z6a7b8",
    type: TransactionType.DEBIT_CARD,
    amount: 1250.0,
    currency: "GBP",
    timestamp: "2026-07-23T14:10:41Z",
    sender_id: "usr_uk_trader",
    receiver_id: "mrc_fx_broker",
    merchant_id: "mrc_fx_broker",
    channel: "online",
    ip_address: "51.148.72.93",
    device_id: "dev_macbook_z3",
    country_code: "GB",
    description: "FX broker deposit - normal pattern",
    status: TransactionStatus.APPROVED,
    risk_score: 0.21,
    risk_level: "LOW",
    risk_verdict: "APPROVE",
    processing_time_ms: 8,
  },
  {
    transaction_id: "txn_c9d0e1f2",
    type: TransactionType.ACH,
    amount: 12500.0,
    currency: "USD",
    timestamp: "2026-07-23T14:08:17Z",
    sender_id: "usr_business_1",
    receiver_id: "usr_supplier",
    channel: "business_banking",
    ip_address: "72.14.192.55",
    country_code: "US",
    description: "Business payment - matches expected pattern",
    status: TransactionStatus.APPROVED,
    risk_score: 0.12,
    risk_level: "VERY_LOW",
    risk_verdict: "APPROVE",
    processing_time_ms: 7,
  },
  {
    transaction_id: "txn_g3h4i5j6",
    type: TransactionType.CREDIT_CARD,
    amount: 4999.0,
    currency: "USD",
    timestamp: "2026-07-23T14:05:33Z",
    sender_id: "usr_8d2f1",
    receiver_id: "mrc_luxury_store",
    merchant_id: "mrc_luxury_store",
    channel: "online",
    ip_address: "185.234.12.44",
    device_id: "dev_iphone15_x1",
    country_code: "NG",
    description: "Same user, different country in 2 minutes",
    status: TransactionStatus.BLOCKED,
    risk_score: 0.96,
    risk_level: "CRITICAL",
    risk_verdict: "BLOCK",
    processing_time_ms: 9,
  },
  {
    transaction_id: "txn_k7l8m9n0",
    type: TransactionType.WIRE_TRANSFER,
    amount: 250.0,
    currency: "EUR",
    timestamp: "2026-07-23T14:02:09Z",
    sender_id: "usr_eu_normal",
    receiver_id: "usr_family_member",
    channel: "online_banking",
    ip_address: "88.217.44.12",
    country_code: "DE",
    description: "Regular monthly family transfer",
    status: TransactionStatus.APPROVED,
    risk_score: 0.04,
    risk_level: "VERY_LOW",
    risk_verdict: "APPROVE",
    processing_time_ms: 6,
  },
];
